# Generated by Django 5.1.15 on 2026-03-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_type', models.CharField(choices=[('jobseeker', 'Jobseeker'), ('employer', 'Employer'), ('admin', 'Admin')], default='jobseeker', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('consented_to_terms', models.BooleanField(default=False)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('is_imported', models.BooleanField(default=False)),
                ('is_claimed', models.BooleanField(default=False)),
                ('claim_token', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='easyhire_users', related_query_name='easyhire_user', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='easyhire_users', related_query_name='easyhire_user', to='auth.permission')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
