# Generated by Django 5.1.15 on 2026-04-08 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_initial'),
        ('jobs', '0001_initial'),
        ('jobseekers', '0004_jobseekerprofile_barangay_and_more'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='employers.company'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='jobseeker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='jobseekers.jobseekerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('jobseeker', 'company', 'job')},
        ),
    ]
