# Generated by Django 5.1.15 on 2026-03-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location_type', models.CharField(choices=[('iloilo', 'Iloilo City'), ('overseas', 'Overseas'), ('remote', 'Remote')], default='iloilo', max_length=10)),
                ('bldg_unit', models.CharField(blank=True, max_length=100)),
                ('street_barangay', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(default='Iloilo City', help_text='Locked to Iloilo City for local jobs.', max_length=100)),
                ('overseas_address', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft')], default='open', max_length=10)),
                ('slots', models.PositiveIntegerField(default=1)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='employers.company')),
            ],
            options={
                'db_table': 'job_postings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobExperienceRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_required', models.PositiveIntegerField(default=0, help_text='Minimum years of experience required. Set to 0 for no experience needed.')),
                ('description', models.TextField(blank=True, help_text="Optional detail — e.g. 'at least 2 years in a retail environment'.")),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='experience_requirement', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'job_experience_requirements',
            },
        ),
        migrations.CreateModel(
            name='JobEducationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('elementary', 'Elementary'), ('junior_high', 'High School / Junior High School'), ('senior_high', 'Senior High School'), ('vocational', 'Vocational / TESDA'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate')], max_length=30)),
                ('course_degree', models.CharField(blank=True, help_text="Optional — e.g. 'BS Computer Science'. Leave blank to accept any course.", max_length=200)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='education_requirement', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'job_education_requirements',
            },
        ),
        migrations.CreateModel(
            name='JobCertificationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_org', models.CharField(blank=True, max_length=200)),
                ('is_required', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_requirements', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'job_certification_requirements',
            },
        ),
        migrations.CreateModel(
            name='JobSkillRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_required', models.BooleanField(default=True, help_text='Required vs preferred — affects weighting in the algorithm.')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='jobs.jobposting')),
            ],
            options={
                'db_table': 'job_skill_requirements',
            },
        ),
    ]
