# Generated by Django 5.1.15 on 2026-04-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobexperiencerequirement',
            name='years_required',
        ),
        migrations.AddField(
            model_name='jobexperiencerequirement',
            name='months_required',
            field=models.PositiveIntegerField(default=0, help_text='Minimum months of experience required. Set to 0 for no experience needed.'),
        ),
        migrations.AlterField(
            model_name='jobexperiencerequirement',
            name='description',
            field=models.TextField(blank=True, help_text="Optional detail — e.g. 'at least 6 months in a retail environment'."),
        ),
    ]
