# Generated by Django 5.1.15 on 2026-04-09 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_remove_jobexperiencerequirement_years_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobexperiencerequirement',
            name='any_experience_accepted',
            field=models.BooleanField(default=True, help_text='If selected, any work experience counts as long as duration is met.'),
        ),
        migrations.AddField(
            model_name='jobexperiencerequirement',
            name='preferred_position',
            field=models.CharField(blank=True, help_text='Preferred previous position/role. Used for fuzzy matching if any_experience_accepted is False.', max_length=200),
        ),
    ]
