# Generated by Django 5.1.15 on 2026-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobexperiencerequirement_any_experience_accepted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='street_barangay',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='barangay_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='barangay_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
