# Generated by Django 5.1.15 on 2026-06-02 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_remove_jobposting_street_barangay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobeducationrequirement',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_requirements', to='jobs.jobposting'),
        ),
    ]
