# Generated by Django 5.1.15 on 2026-06-07 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_application_status_viewed_hired'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='employed_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='hired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
