# Generated by Django 5.1.15 on 2026-06-30 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobposting_admin_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('viewed', 'Viewed'), ('accepted', 'In Progress'), ('rejected', 'Rejected'), ('hire_pending', 'Hire Offered'), ('hired', 'Hired')], default='pending', max_length=15),
        ),
    ]
