# Generated by Django 5.1.15 on 2026-07-02 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_alter_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.jobposting'),
        ),
    ]
