# Generated by Django 5.1.15 on 2026-08-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_jobposting_deleted_at_alter_application_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='externally_hired_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
