# Generated by Django 5.1.15 on 2026-08-08 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_jobposting_externally_hired_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('members', 'Registered EasyHire Only')], default='public', help_text='Public jobs appear on the marketing site; members-only jobs are hidden from anonymous visitors.', max_length=10),
        ),
    ]
