# Generated by Django 5.1.15 on 2026-08-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobposting_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='admin_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='admin_deleted_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
