# Generated by Django 5.1.15 on 2026-08-09 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inboxuserstate'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='inboxuserstate',
            new_name='inbox_user__user_id_c0e9f2_idx',
            old_name='inbox_user__user_id_dismis_idx',
        ),
        migrations.RenameIndex(
            model_name='inboxuserstate',
            new_name='inbox_user__user_id_8e1509_idx',
            old_name='inbox_user__user_id_pinned_idx',
        ),
        migrations.AddField(
            model_name='inboxuserstate',
            name='is_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inboxuserstate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
