# Generated by Django 5.1.15 on 2026-03-12 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'candidate_interactions',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('type_of_company', models.CharField(choices=[('local', 'Local'), ('overseas', 'Overseas'), ('bpo', 'BPO')], help_text='Determines which verification documents are required.', max_length=20)),
                ('nature_of_company', models.CharField(help_text='e.g. School, University, Hospital, Retail. Free text with suggestions.', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('company_size', models.CharField(blank=True, max_length=50)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_email', models.EmailField(max_length=254)),
                ('recruitment_email', models.EmailField(max_length=254)),
                ('main_branch_address', models.CharField(max_length=300)),
                ('iloilo_bldg_unit', models.CharField(blank=True, max_length=100)),
                ('iloilo_street_barangay', models.CharField(max_length=200)),
                ('iloilo_city', models.CharField(default='Iloilo City', max_length=100)),
                ('iloilo_province', models.CharField(default='Iloilo', max_length=100)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verification_denied', 'Verification Denied'), ('verified', 'Verified')], default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_note', models.TextField(blank=True)),
                ('is_peso_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('position', models.CharField(help_text="Representative's position/role in the company", max_length=200)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employer_profiles',
            },
        ),
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('mayors_permit', "Business/Mayor's Permit"), ('philjobnet_accreditation', 'PhilJobNet Proof of Accreditation'), ('philjobnet_dashboard', 'Screenshot of PhilJobNet Posting Dashboard'), ('job_vacancies_list', 'List of Job Vacancies'), ('pea_license', 'Private Employment Agency (PEA) License (DOLE)'), ('do174_certificate', 'D.O. 174 Series of 2017 Certificate (DOLE)'), ('poea_license', 'POEA Certificate of License'), ('job_order', 'Approved Job Balance Order')], max_length=50)),
                ('file', models.FileField(upload_to='employer_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'verification_documents',
            },
        ),
    ]
