# Generated by Django 5.1.15 on 2026-03-12 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('jobs', '0001_initial'),
        ('jobseekers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateinteraction',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_candidate_interactions', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='candidateinteraction',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employer_interactions', to='jobseekers.jobseekerprofile'),
        ),
        migrations.AddField(
            model_name='company',
            name='sector_badges',
            field=models.ManyToManyField(blank=True, related_name='companies', to='jobseekers.sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateinteraction',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_interactions', to='employers.company'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='representatives', to='employers.company'),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='verificationdocument',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_docs', to='employers.company'),
        ),
        migrations.AlterUniqueTogether(
            name='candidateinteraction',
            unique_together={('company', 'jobseeker', 'job')},
        ),
    ]
