# Generated by Django 5.1.15 on 2026-04-09 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='iloilo_street_barangay',
        ),
        migrations.AddField(
            model_name='company',
            name='iloilo_barangay_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='iloilo_barangay_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='company',
            name='iloilo_street',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
