# Generated by Django 5.1.15 on 2026-06-11 12:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_remove_company_iloilo_street_barangay_and_more'),
        ('jobs', '0010_application_hire_dates'),
        ('jobseekers', '0012_work_experience_from_application'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('requirements', 'Job Requirements'), ('interview', 'Interview Schedule')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('interview_at', models.DateTimeField(blank=True, null=True)),
                ('interview_location', models.CharField(blank=True, default='', max_length=200)),
                ('delivered_to_email', models.EmailField(blank=True, default='', help_text='Snapshot of the email address we tried to deliver to.', max_length=254)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='employers.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='jobs.jobposting')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contacts', to='jobseekers.jobseekerprofile')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employer_contacts',
                'ordering': ['-sent_at'],
            },
        ),
    ]
