# Generated by Django 5.1.15 on 2026-07-05 14:15

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_employercontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationdocument',
            name='file',
            field=models.FileField(storage=apps.core.storage.raw_media_storage, upload_to='employer_docs/'),
        ),
    ]
