# Generated by Django 5.1.15 on 2026-07-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_alter_verificationdocument_file'),
        ('jobseekers', '0015_alter_jobseekerprofile_id_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='pending_sector_badges',
            field=models.ManyToManyField(blank=True, related_name='pending_companies', to='jobseekers.sector'),
        ),
        migrations.AddField(
            model_name='company',
            name='sectors_change_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='sectors_change_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
