# Generated by Django 5.1.15 on 2026-03-12 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('fresh_graduate', 'Fresh Graduate'), ('lgbtqia', 'LGBTQIA++'), ('osy', 'Out-of-School Youth (OSY)'), ('pwd', 'Persons with Disabilities (PWD)'), ('senior_citizen', 'Senior Citizen'), ('solo_parent', 'Solo Parent'), ('tesda_graduate', 'TESDA Graduate')], max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='JobseekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=30)),
                ('house_unit', models.CharField(blank=True, max_length=100)),
                ('street_barangay', models.CharField(max_length=200)),
                ('city_municipality', models.CharField(default='Iloilo City', max_length=100)),
                ('province', models.CharField(default='Iloilo', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('job_search_query', models.CharField(blank=True, max_length=255)),
                ('profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followed_companies', models.ManyToManyField(blank=True, related_name='followers', to='employers.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_profile', to=settings.AUTH_USER_MODEL)),
                ('sectors', models.ManyToManyField(blank=True, related_name='jobseekers', to='jobseekers.sector')),
            ],
            options={
                'db_table': 'jobseeker_profiles',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('elementary', 'Elementary'), ('junior_high', 'High School / Junior High School'), ('senior_high', 'Senior High School'), ('vocational', 'Vocational / TESDA'), ('associate', 'Associate Degree'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate')], max_length=30)),
                ('course_degree', models.CharField(blank=True, max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('year_started', models.PositiveIntegerField(blank=True, null=True)),
                ('year_ended', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text="I'm still attending this institution.")),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobseeker_educations',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuing_org', models.CharField(blank=True, max_length=200)),
                ('year_received', models.PositiveIntegerField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobseeker_certifications',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobseeker_skills',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('month_started', models.CharField(blank=True, max_length=20)),
                ('year_started', models.PositiveIntegerField(blank=True, null=True)),
                ('month_ended', models.CharField(blank=True, max_length=20)),
                ('year_ended', models.PositiveIntegerField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False, help_text="I'm still employed under this position.")),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobseeker_experiences',
            },
        ),
        migrations.CreateModel(
            name='JobInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('liked', 'Liked'), ('hidden', 'Hidden')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobseeker_interactions', to='jobs.jobposting')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_interactions', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'db_table': 'jobseeker_job_interactions',
                'unique_together': {('jobseeker', 'job')},
            },
        ),
    ]
