# Generated by Django 5.1.15 on 2026-03-12 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='city_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='province_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
