# Generated by Django 5.1.15 on 2026-03-23 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0002_jobseekerprofile_city_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
