# Generated by Django 5.1.15 on 2026-04-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0003_jobseekerprofile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='barangay',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='barangay_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
