# Generated by Django 5.1.15 on 2026-04-09 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0004_jobseekerprofile_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
