# Generated by Django 5.1.15 on 2026-06-05 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0009_seed_sectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfoChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, default='', max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, default='', max_length=10)),
                ('id_type', models.CharField(help_text='Which Philippine ID the jobseeker will present to PESO.', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='info_change_requests', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'db_table': 'personal_info_change_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
