# Generated by Django 5.1.15 on 2026-06-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0010_personal_info_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfochangerequest',
            name='id_document',
            field=models.FileField(blank=True, help_text='Uploaded photo/scan of a valid Philippine ID for PESO verification.', null=True, upload_to='personal_info_ids/'),
        ),
        migrations.AlterField(
            model_name='personalinfochangerequest',
            name='id_type',
            field=models.CharField(blank=True, default='', help_text='Optional — admin notes which ID type was provided. The jobseeker no longer picks this; they just upload.', max_length=50),
        ),
    ]
