# Generated by Django 5.1.15 on 2026-06-07 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_application_hire_dates'),
        ('jobseekers', '0011_change_request_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='from_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_experiences', to='jobs.application'),
        ),
    ]
