# Generated by Django 5.1.15 on 2026-07-01 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0012_work_experience_from_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional context about this skill (years of experience, tools, notable projects).'),
        ),
    ]
