# Generated by Django 5.1.15 on 2026-07-04 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0013_skill_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='id_document',
            field=models.FileField(blank=True, help_text='Uploaded photo/scan of a valid Philippine government ID.', null=True, upload_to='jobseeker_ids/'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='id_submitted_at',
            field=models.DateTimeField(blank=True, help_text='When the jobseeker submitted their ID for review.', null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='id_verification_note',
            field=models.TextField(blank=True, default='', help_text='Admin note attached to a Denied verification — surfaced to the jobseeker.'),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='id_verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending Review'), ('verified', 'Verified'), ('denied', 'Denied')], default='unverified', max_length=20),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='id_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='id_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_jobseekers', to=settings.AUTH_USER_MODEL),
        ),
    ]
