# Generated by Django 5.1.15 on 2026-07-05 14:15

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekers', '0014_jobseekerprofile_id_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='id_document',
            field=models.FileField(blank=True, help_text='Uploaded photo/scan of a valid Philippine government ID.', null=True, storage=apps.core.storage.raw_media_storage, upload_to='jobseeker_ids/'),
        ),
        migrations.AlterField(
            model_name='personalinfochangerequest',
            name='id_document',
            field=models.FileField(blank=True, help_text='Uploaded photo/scan of a valid Philippine ID for PESO verification.', null=True, storage=apps.core.storage.raw_media_storage, upload_to='personal_info_ids/'),
        ),
    ]
