# Generated by Django 5.1.15 on 2026-03-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0002_initial'),
        ('jobs', '0001_initial'),
        ('jobseekers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompatibilityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Overall compatibility 0–100.')),
                ('breakdown', models.JSONField(default=dict, help_text='Stores per-category scores and matched/missing details.')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('is_stale', models.BooleanField(default=False, help_text='Set True when resume or job requirements change to trigger recompute.')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores', to='jobs.jobposting')),
                ('jobseeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_scores', to='jobseekers.jobseekerprofile')),
            ],
            options={
                'db_table': 'compatibility_scores',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='employers.company')),
            ],
            options={
                'db_table': 'matches',
            },
        ),
    ]
