# Generated by Django 5.1.15 on 2026-03-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        ('jobseekers', '0001_initial'),
        ('matching', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='match',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobs.jobposting'),
        ),
        migrations.AddField(
            model_name='match',
            name='jobseeker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='jobseekers.jobseekerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='compatibilityscore',
            unique_together={('jobseeker', 'job')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('jobseeker', 'company', 'job')},
        ),
    ]
