"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Loaded from .env; never commit a real key to source control.
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-dev-only-replace-via-env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [h.strip() for h in os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',') if h.strip()]

# CSRF: trust the same hosts over HTTPS in production.
CSRF_TRUSTED_ORIGINS = [
    ('https://' if not h.startswith(('http://', 'https://')) else '') + h
    for h in ALLOWED_HOSTS
    if h not in ('localhost', '127.0.0.1', '*')
]

AUTH_USER_MODEL = 'accounts.User'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',

    # Allauth
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    # EasyHire apps
    'apps.accounts',
    'apps.jobseekers',
    'apps.employers',
    'apps.jobs',
    'apps.matching',
    'apps.messaging',
    'apps.analytics',
    'apps.admin_panel',
    
    'apps.core',
    'apps.notifications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'apps.accounts.middleware.NoCacheAuthenticatedMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.accounts.context_processors.email_verification_status',
                'apps.core.context_processors.inbox_status',
                'apps.core.context_processors.notifications_baseline',
            ],
            'builtins': [
                'apps.core.templatetags.hashid_tags',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'easyhire'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# If DATABASE_URL is set (Render's Postgres add-on provides this), it wins.
_db_url = os.getenv('DATABASE_URL')
print(f"[settings] DEBUG={DEBUG}  DATABASE_URL_set={bool(_db_url)}", flush=True)
if _db_url:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(
        default=_db_url,
        conn_max_age=600,
        ssl_require=True,
    )
    print(f"[settings] DB host parsed: {DATABASES['default'].get('HOST', '?')}", flush=True)
else:
    # Hard-fail if we're on Render (or any env that isn't local dev)
    if os.getenv('RENDER') or os.getenv('IS_PRODUCTION') or not DEBUG:
        raise RuntimeError(
            "DATABASE_URL environment variable is not set. "
            "On Render: web service -> Environment tab -> add DATABASE_URL "
            "with the Internal Database URL from your Postgres service. "
            "Then click Save Changes AND trigger Manual Deploy -> Deploy latest commit."
        )


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Media (user-uploaded files: profile pictures, ID documents, company logos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Storage backends:
# - Static files: always WhiteNoise (compressed + hashed for cache busting).
# - Media files: local filesystem by default, Cloudinary when CLOUDINARY_URL is set.
CLOUDINARY_URL = os.getenv('CLOUDINARY_URL', '')

STORAGES = {
    'default': {
        'BACKEND': (
            'cloudinary_storage.storage.MediaCloudinaryStorage'
            if CLOUDINARY_URL else
            'django.core.files.storage.FileSystemStorage'
        ),
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if CLOUDINARY_URL:
    INSTALLED_APPS += ['cloudinary_storage', 'cloudinary']

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ── Auth ──────────────────────────────────────────────────────────
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'

# ── Session Security ──────────────────────────────────────────────
# Keep sessions persistent across browser restarts so Render cold-starts
# and tab closures don't surprise-logout users. SESSION_COOKIE_AGE
# controls the actual lifetime.
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_AGE = 60 * 60 * 24 * 14  # 14 days
SESSION_SAVE_EVERY_REQUEST = True       # slides the expiry forward on every request
SESSION_COOKIE_HTTPONLY = True

# Render terminates TLS at its edge proxy and forwards as HTTP. Without
# this header Django doesn't know the original request was HTTPS, which
# trips up secure cookies + redirects.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# ── Sites ──────────────────────────────────────────────────────────
SITE_ID = 1

# ── Authentication backends ────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# ── Allauth account settings ───────────────────────────────────────
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# Optional verification: users can log in immediately, but unverified accounts see
# a banner prompting them to confirm their email. allauth handles the link + resend.
# (Email is already required via ACCOUNT_SIGNUP_FIELDS above.)
ACCOUNT_EMAIL_VERIFICATION = 'optional'
ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS = 7

# ── Email backend ──────────────────────────────────────────────────
# In dev (no SMTP credentials set), emails print to the console.
# In prod, configure EMAIL_HOST_USER + EMAIL_HOST_PASSWORD via env.
if os.getenv('EMAIL_HOST_USER'):
    EMAIL_BACKEND       = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST          = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT          = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS       = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER     = os.getenv('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL  = os.getenv('DEFAULT_FROM_EMAIL', f'EasyHire <{EMAIL_HOST_USER}>')
else:
    EMAIL_BACKEND      = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'EasyHire <noreply@easyhire.local>'
ACCOUNT_ADAPTER = 'apps.accounts.adapters.AccountAdapter'

# ── Allauth social account settings ───────────────────────────────
SOCIALACCOUNT_ADAPTER = 'apps.accounts.adapters.SocialAccountAdapter'
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_LOGIN_ON_GET = True
SOCIALACCOUNT_STORE_TOKENS = False
SOCIALACCOUNT_EMAIL_AUTHENTICATION = True
SOCIALACCOUNT_EMAIL_AUTHENTICATION_AUTO_CONNECT = True

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    }
}
