# Generated by Django 5.1.15 on 2026-03-12 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verify', 'Verified Company'), ('reject', 'Rejected Verification'), ('deactivate', 'Deactivated Account'), ('reactivate', 'Reactivated Account'), ('import', 'Imported Records'), ('edit', 'Edited Record'), ('delete', 'Deleted Record'), ('reset_password', 'Reset Password')], max_length=30)),
                ('target_model', models.CharField(help_text="The model that was acted on e.g. 'Company', 'JobseekerProfile'.", max_length=100)),
                ('target_id', models.PositiveIntegerField(help_text='The primary key of the record that was acted on.')),
                ('notes', models.TextField(blank=True, help_text='Optional notes e.g. reason for rejection or deactivation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(choices=[('jobseekers', 'Jobseekers'), ('companies', 'Companies')], max_length=20)),
                ('file', models.FileField(upload_to='imports/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('successful_imports', models.PositiveIntegerField(default=0)),
                ('failed_imports', models.PositiveIntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=list, help_text='List of row-level errors encountered during import.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'import_batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compatibility_threshold', models.FloatField(default=80.0, help_text="Minimum compatibility score to trigger a 'New Compatible Job' notification.")),
                ('hard_to_fill_days', models.PositiveIntegerField(default=30, help_text='Number of days a job must be open before being flagged as hard to fill.')),
                ('hard_to_fill_applicant_threshold', models.PositiveIntegerField(default=3, help_text='Maximum applicant count for a job to be considered hard to fill.')),
                ('max_hide_suggestions', models.PositiveIntegerField(default=5, help_text='Number of hidden jobs from the same company before suggesting a bulk hide.')),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Puts the site in maintenance mode — only admins can log in.')),
                ('maintenance_message', models.TextField(blank=True, help_text='Message shown to users during maintenance mode.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
    ]
