# Generated by Django 5.1.15 on 2026-06-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_user_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='weight_certifications',
            field=models.FloatField(default=0.1, help_text='Weight for certifications match (0.0-1.0).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weight_education',
            field=models.FloatField(default=0.25, help_text='Weight for education match (0.0-1.0).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weight_experience',
            field=models.FloatField(default=0.25, help_text='Weight for experience match (0.0-1.0).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='weight_skills',
            field=models.FloatField(default=0.4, help_text='Weight for skills match in the compatibility score (0.0-1.0).'),
        ),
    ]
