# Generated by Django 5.1.15 on 2026-06-15 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_algorithm_weights'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('all', 'All Users'), ('jobseekers', 'Jobseekers Only'), ('employers', 'Employers Only')], default='all', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_announcements',
                'ordering': ['-sent_at'],
            },
        ),
    ]
