# Generated by Django 5.1.15 on 2026-07-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_site_contact_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='compatibility_threshold',
            field=models.FloatField(default=80.0, help_text="Minimum compatibility score to trigger a 'A New Job for You was Posted' notification."),
        ),
    ]
