# Generated by Django 5.1.15 on 2026-07-01 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0006_alter_sitesettings_compatibility_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(help_text='Basic HTML allowed (rendered with |safe).')),
                ('audience', models.CharField(choices=[('jobseeker', 'Jobseeker'), ('employer', 'Employer'), ('both', 'Both')], default='jobseeker', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first within an audience.')),
                ('is_published', models.BooleanField(default=True, help_text='Uncheck to hide a FAQ without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'faqs',
                'ordering': ['audience', 'order', 'id'],
            },
        ),
    ]
