# Generated by Django 5.1.15 on 2026-07-04 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_seed_faqs'),
        ('jobs', '0014_jobposting_deleted_at_alter_application_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='reported_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='jobs.jobposting'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='account_type',
            field=models.CharField(choices=[('jobseeker', 'Jobseeker'), ('employer', 'Employer'), ('job', 'Job Post')], max_length=20),
        ),
    ]
