# Generated by Django 5.1.15 on 2026-07-04 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_userreport_reported_job_and_more'),
        ('employers', '0004_employercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='reported_contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='employers.employercontact'),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='account_type',
            field=models.CharField(choices=[('jobseeker', 'Jobseeker'), ('employer', 'Employer'), ('job', 'Job Post'), ('contact', 'Message')], max_length=20),
        ),
    ]
