# Generated by Django 5.1.15 on 2026-07-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0010_userreport_reported_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='resolution_note',
            field=models.CharField(blank=True, default='', help_text='Short summary of the action taken — surfaced in the Notes column of the reports list.', max_length=200),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='status',
            field=models.CharField(choices=[('open', 'Pending'), ('reviewed', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=20),
        ),
    ]
