# Generated by Django 5.1.15 on 2026-07-05 14:15

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0011_userreport_resolution_note_alter_userreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importbatch',
            name='file',
            field=models.FileField(storage=apps.core.storage.raw_media_storage, upload_to='imports/'),
        ),
    ]
