# Generated by Django 5.1.15 on 2026-03-12 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_jobseekers', models.PositiveIntegerField(default=0)),
                ('total_employers', models.PositiveIntegerField(default=0)),
                ('new_jobseekers', models.PositiveIntegerField(default=0, help_text='New jobseekers registered on this date.')),
                ('new_employers', models.PositiveIntegerField(default=0, help_text='New employers registered on this date.')),
                ('total_job_postings', models.PositiveIntegerField(default=0)),
                ('active_job_postings', models.PositiveIntegerField(default=0)),
                ('new_job_postings', models.PositiveIntegerField(default=0)),
                ('hard_to_fill_jobs', models.PositiveIntegerField(default=0)),
                ('jobs_placed', models.PositiveIntegerField(default=0, help_text='Total mutual matches recorded up to this date.')),
                ('new_matches', models.PositiveIntegerField(default=0, help_text='New matches created on this date.')),
                ('avg_compatibility_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'daily_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InDemandSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('skill_name', models.CharField(max_length=200)),
                ('job_count', models.PositiveIntegerField(default=0, help_text='Number of active job postings requiring this skill.')),
                ('avg_compatibility', models.FloatField(blank=True, help_text='Average compatibility score of jobseekers for jobs requiring this skill.', null=True)),
            ],
            options={
                'db_table': 'in_demand_skills',
                'ordering': ['-week_start', '-job_count'],
                'unique_together': {('week_start', 'skill_name')},
            },
        ),
        migrations.CreateModel(
            name='LocationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('barangay', models.CharField(max_length=200)),
                ('jobseeker_count', models.PositiveIntegerField(default=0)),
                ('job_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'location_snapshots',
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'barangay')},
            },
        ),
        migrations.CreateModel(
            name='CompanyTypeSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_type', models.CharField(max_length=50)),
                ('company_type_label', models.CharField(max_length=100)),
                ('company_count', models.PositiveIntegerField(default=0)),
                ('active_job_count', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_type_breakdown', to='analytics.dailysnapshot')),
            ],
            options={
                'db_table': 'company_type_snapshots',
                'unique_together': {('snapshot', 'company_type')},
            },
        ),
        migrations.CreateModel(
            name='EducationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=50)),
                ('level_label', models.CharField(max_length=100)),
                ('jobseeker_count', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_breakdown', to='analytics.dailysnapshot')),
            ],
            options={
                'db_table': 'education_snapshots',
                'unique_together': {('snapshot', 'level')},
            },
        ),
        migrations.CreateModel(
            name='SectorSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_code', models.CharField(max_length=50)),
                ('sector_label', models.CharField(max_length=100)),
                ('jobseeker_count', models.PositiveIntegerField(default=0)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sector_breakdown', to='analytics.dailysnapshot')),
            ],
            options={
                'db_table': 'sector_snapshots',
                'unique_together': {('snapshot', 'sector_code')},
            },
        ),
    ]
