# Generated by Django 5.1.15 on 2026-04-09 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0003_remove_company_iloilo_street_barangay_and_more'),
        ('jobs', '0005_remove_jobposting_street_barangay_and_more'),
        ('jobseekers', '0005_jobseekerprofile_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('company_liked_you', 'Company Liked You'), ('jobseekers_liked_job', 'Jobseekers Liked Job'), ('match', 'Match')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liker_count', models.PositiveIntegerField(default=1)),
                ('liker_preview', models.CharField(blank=True, help_text="e.g. 'Juan, Maria and 9+ others'", max_length=200)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employers.company')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('jobseeker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobseekers.jobseekerprofile')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
