# Generated by Django 5.1.15 on 2026-06-07 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_application_hire_dates'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='admin_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.jobposting'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='liker_preview',
            field=models.CharField(blank=True, help_text="e.g. 'Juan, Maria and 9+ others', or a deleted job's title snapshot.", max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('company_liked_you', 'Company Liked You'), ('jobseekers_liked_job', 'Jobseekers Liked Job'), ('match', 'Match'), ('job_deleted_by_admin', 'Job Deleted by Admin')], max_length=30),
        ),
    ]
