# Generated by Django 5.1.15 on 2026-06-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_job_deletion_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('company_liked_you', 'Company Liked You'), ('jobseekers_liked_job', 'Jobseekers Liked Job'), ('match', 'Match'), ('job_deleted_by_admin', 'Job Deleted by Admin'), ('personal_info_approved', 'Personal Info Change Approved'), ('personal_info_rejected', 'Personal Info Change Rejected')], max_length=30),
        ),
    ]
